#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define MODBUS_ADDR     1

#define MODBUS_PWM0_REG		10
#define MODBUS_PWM1_REG		11
#define MODBUS_PWM2_REG		12

#define MODBUS_BASE_STATUS_REG	1
#define MODBUS_BASE_UPTIME_REG	2
#define MODBUS_BASE_VIN_REG	5
#define MODBUS_BASE_IIN_REG	6
#define MODBUS_BASE_3V3_REG	7
#define MODBUS_BASE_TEMPINT_REG	8

#define MODBUS_TEMP0_REG		200
#define MODBUS_N_THERMOMETERS	2
#define MODBUS_TEMP_MAX_AGE	10

#endif